sudo: required

services:
- docker

language: bash

branches:
  only:
  - master

script:
  - VERSION=`curl https://github.com/home-assistant/homebridge-homeassistant/releases/latest -s -L -I -o /dev/null -w '%{url_effective}' | sed 's#.*/##'`
  # Build ARM docker image
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -f ./arm/Dockerfile -t basbloembergen/rpi-homebridge-homeassistant:${VERSION} --build-arg VERSION=${VERSION} .

after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

    docker push basbloembergen/rpi-homebridge-homeassistant:${VERSION}
    docker tag basbloembergen/rpi-homebridge-homeassistant:${VERSION} basbloembergen/rpi-homebridge-homeassistant:latest
    docker push basbloembergen/rpi-homebridge-homeassistant:latest
  fi
